solved the optimize-component error
the issue was when calling the main function in optimize-performance.sh that gets the details of the OS from previous common.sh script, but here it gave error detect_os_version not found so that was solved by adding (Search for common.sh in the current directory and parent directory) block, next step is adding the reboot-os component

diff --git a/components/install-cloudwatch-agent.yaml b/components/install-cloudwatch-agent.yaml
--- a/components/install-cloudwatch-agent.yaml
+++ b/components/install-cloudwatch-agent.yaml
@@ -147,7 +147,15 @@ phases:
               # Find the directory of the current script
               SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 
-              # common.sh injected via Terraform
+                # Search for common.sh in the current directory and parent directory
+                if [ -f "${SCRIPT_DIR}/common.sh" ]; then
+                    . "${SCRIPT_DIR}/common.sh"
+                elif [ -f "${SCRIPT_DIR}/../common.sh" ]; then
+                    . "${SCRIPT_DIR}/../common.sh"
+                else
+                    echo "Error: common.sh not found!" >&2
+                    exit 1
+                fi
 
               handle_ubuntu_22.04() {
                   logger "Installing on Ubuntu 22.04" "INFO"
diff --git a/components/optimize-performance.yaml b/components/optimize-performance.yaml
--- a/components/optimize-performance.yaml
+++ b/components/optimize-performance.yaml
@@ -3,7 +3,7 @@ schemaVersion: 1.0
 phases:
   - name: build
     steps:
-### Embedding the update-os.sh and common.sh scripts directly here for testing purposes
+### Embedding the optimize-performance.sh and common.sh scripts directly here for testing purposes
       - name: WriteAndRunScripts
         action: ExecuteBash
         inputs:
@@ -146,7 +146,15 @@ phases:
                 # Find the directory of the current script
                 SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 
-                # common.sh injected via Terraform
+                # Search for common.sh in the current directory and parent directory
+                if [ -f "${SCRIPT_DIR}/common.sh" ]; then
+                    . "${SCRIPT_DIR}/common.sh"
+                elif [ -f "${SCRIPT_DIR}/../common.sh" ]; then
+                    . "${SCRIPT_DIR}/../common.sh"
+                else
+                    echo "Error: common.sh not found!" >&2
+                    exit 1
+                fi                
 
                 disable_select_cron_tasks() {
 
