created cloudwatch-agent.yaml and optimize-performance.yaml files

diff --git a/components/optimize-performance.yaml b/components/optimize-performance.yaml
--- a/components/optimize-performance.yaml
+++ b/components/optimize-performance.yaml
@@ -1,27 +1,271 @@
-      Name: !Sub 'OptimizePerformance-${AWS::StackName}'
-      Description: Optimize HPC application peformance on PCS-compatible AMI
-      Version: '0.0.1'
-      Platform: Linux
-      Data: !Sub |
-        name: 'Optimize HPC application performance'
-        schemaVersion: 1.0
-        phases:
-          - name: build
-            steps:
-              - name: DownloadCommon
-                action: WebDownload
-                inputs:
-                  - source: https://${HpcRecipesS3Bucket}.s3.us-east-1.amazonaws.com/${HpcRecipesBranch}/recipes/pcs/hpc_ready_ami/assets/scripts/common.sh
-                    destination: common.sh
-              - name: DownloadOptimizeScript
-                action: WebDownload
-                inputs:
-                  - source: https://${HpcRecipesS3Bucket}.s3.us-east-1.amazonaws.com/${HpcRecipesBranch}/recipes/pcs/hpc_ready_ami/assets/scripts/optimize-performance.sh
-                    destination: optimize-performance.sh
-              - name: ExecuteOptimizeScript
-                action: ExecuteBash
-                inputs:
-                  commands:
-                    - set -e
-                    - 'chmod +x optimize-performance.sh'
-                    - './optimize-performance.sh'
+name: 'OptimizePerformance for PCS AMI'
+schemaVersion: 1.0
+phases:
+  - name: build
+    steps:
+### Embedding the update-os.sh and common.sh scripts directly here for testing purposes
+      - name: WriteAndRunScripts
+        action: ExecuteBash
+        inputs:
+          commands:
+            - set -e
+            - |
+              cat << 'EOF' > common.sh
+              
+                    #!/usr/bin/env bash
+
+                    # This script update the OS and base packages for AMIs from 
+                    # operating systems supported by AWS PCS. It is intended to 
+                    # replace the UpdateOS ImageBuilder component with a solution
+                    # that is more flexible to the specifics of each supported OS.
+                    #
+                    # Exports OS, VERSION, ARCHITECTURE variables
+
+                    set -o errexit -o pipefail -o nounset
+
+                    OS=""
+                    VERSION=""
+                    ARCHITECTURE=""
+
+                    # Function to log
+                    logger() {
+                      local script="$0";
+                      local log_message="$1";
+                      local log_level="${2:-INFO}";
+                      local timestamp=$(date +"%Y-%m-%dT%H:%M:%S.%3N%:z");
+                      echo "[$timestamp] - $script: $log_level: $log_message";
+                    }
+
+                    # These are stub functions. In scripts that import common.sh, we expect to find
+                    # functions defined with the same names, one for each OS/version combination.
+                    # 
+                    # If the function isn't defined in the script, it will fall back to the one defined here.
+
+                    handle_ubuntu_22.04() {
+                        logger "Default for Ubuntu 22.04" "WARNING"
+                        export DEBIAN_FRONTEND=noninteractive
+                        export APT_LISTCHANGES_FRONTEND=none
+                    }
+
+                    handle_rhel_9() { 
+                        logger "Default for RHEL 9" "WARNING"
+                    }
+
+                    handle_rocky_9() {
+                        logger "Default for Rocky Linux 9" "WARNING"
+
+
+                        
+                    }
+
+                    handle_amzn_2() {
+                        logger "Default for Amazon Linux 2" "WARNING"
+                    }
+
+                    detect_os_version() {
+
+                        ARCHITECTURE=$(uname -m)
+
+                        # Detect the operating system
+                        if [ -f /etc/os-release ]; then
+                            # Read the contents of the /etc/os-release file
+                            # shellcheck disable=SC1091
+                            . /etc/os-release
+                            # Extract the operating system ID and version
+                            OS=$ID
+                            VERSION=$VERSION_ID
+                        else
+                            logger "Unable to detect the operating system." "ERROR"
+                            exit 1
+                        fi
+
+                        # Verify if the OS is supported
+                        case "$OS" in
+                            ubuntu)
+                                if [ "$VERSION" == "22.04" ]; then
+                                    logger "Detected OS: $OS, Version: $VERSION, Architecture: $ARCHITECTURE" "INFO"
+                                else
+                                    logger "Unsupported Ubuntu version: $VERSION" "ERROR"
+                                    exit 1
+                                fi
+                                ;;
+                            rhel)
+                                if [[ "$VERSION" =~ ^9\.* ]]; then
+                                    VERSION=9
+                                    logger "Detected OS: $OS, Version: $VERSION, Architecture: $ARCHITECTURE" "INFO"
+                                else
+                                    logger "Unsupported RHEL version: $VERSION" "ERROR"
+                                    exit 1
+                                fi
+                                ;;
+                            rocky)
+                                if [[ "$VERSION" =~ ^9\.* ]]; then
+                                    VERSION=9
+                                    logger "Detected OS: $OS, Version: $VERSION, Architecture: $ARCHITECTURE" "INFO"
+                                else
+                                    logger "Unsupported Rocky Linux version: $VERSION" "ERROR"
+                                    exit 1
+                                fi
+                                ;;
+                            amzn)
+                                if [ "$VERSION" == "2" ]; then
+                                    logger "Detected OS: $OS, Version: $VERSION, Architecture: $ARCHITECTURE" "INFO"
+                                else
+                                    logger "Unsupported Amazon Linux version: $VERSION" "ERROR"
+                                    exit 1
+                                fi
+                                ;;
+                            *)
+                                logger "Unsupported operating system: $OS" "ERROR"
+                                exit 1
+                                ;;
+                        esac
+
+                        export OS
+                        export VERSION
+                        export ARCHITECTURE
+
+                    }
+
+
+
+
+              EOF
+
+            
+            - |
+              cat << 'EOF' > optimize-performance.sh
+                #!/usr/bin/env bash
+
+                # This script applies generalized performance optimizations
+                # AMIs built for AWS PCS. It should be run after core system 
+                # packages are upgradded or installed.
+
+                set -o errexit -o pipefail -o nounset
+
+                # Find the directory of the current script
+                SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
+
+                # common.sh injected via Terraform
+
+                disable_select_cron_tasks() {
+
+                # Disable cron job tasks man-db and mlocate, which may have a negative impact on node performance. 1496 and 1494
+                # Ref: https://github.com/aws/aws-parallelcluster-cookbook/pull/1496
+                # Ref https://github.com/aws/aws-parallelcluster-cookbook/pull/1494
+
+                    logger "Disabling select cron tasks" "INFO"
+
+                    [ -d "/etc/cron.daily" ] || sudo mkdir -m 755 "/etc/cron.daily"
+                    for task in man-db man-db.cron mlocate; do
+                        if [ ! -f "/etc/cron.daily/jobs.deny" ] || ! grep -qxF "$task" "/etc/cron.daily/jobs.deny"; then
+                            echo "$task" | sudo tee -a "/etc/cron.daily/jobs.deny" > /dev/null
+                        fi
+                    done
+                    [ -d "/etc/cron.weekly" ] || sudo mkdir -m 755 "/etc/cron.weekly"
+                    for task in man-db; do
+                        if [ ! -f "/etc/cron.weekly/jobs.deny" ] || ! grep -qxF "$task" "/etc/cron.weekly/jobs.deny"; then
+                            echo "$task" | sudo tee -a "/etc/cron.weekly/jobs.deny" > /dev/null
+                        fi
+                    done
+                }
+
+                disable_deeper_cstates() {
+
+                # Disable deeper C-States in x86_64 official AMIs and AMIs created through build-image command, to guarantee high performance and low latency. - 1386
+                # Ref: https://github.com/aws/aws-parallelcluster-cookbook/pull/1386
+
+                    if [ "${ARCHITECTURE}" == "x86_64" ]; then
+
+                        logger "Disabling deeper C-States" "INFO"
+
+                        # See https://github.com/aws/aws-parallelcluster-cookbook/commit/1f5911817d10b9ca00a706c94d50ef5e756b81e7
+                        case "${OS}-${VERSION}" in
+                            r*-9 )
+                                sudo grubby --update-kernel=ALL --args="intel_idle.max_cstate=1 processor.max_cstate=1"
+                                ;;
+                            ubuntu* )
+                                sudo sed -i '/^GRUB_CMDLINE_LINUX=".*"$/s/"$/ intel_idle.max_cstate=0 processor.max_cstate=1"/' /etc/default/grub
+                                sudo /usr/sbin/update-grub
+                                ;;
+                            *)
+                                sudo sed -i '/^GRUB_CMDLINE_LINUX_DEFAULT=".*"$/s/"$/ intel_idle.max_cstate=0 processor.max_cstate=1"/' /etc/default/grub
+                                sudo /usr/sbin/grub2-mkconfig -o /boot/grub2/grub.cfg
+                                ;;
+                        esac
+                    else
+                        logger "Non x86 architecture detected, skipping C-States optimization" "INFO"
+                    fi
+                }
+
+                custom_sysctl_settings() {
+
+                # Configure the following default gc_thresh values for performance at scale.
+                # - net.ipv4.neigh.default.gc_thresh1 = 0
+                # - net.ipv4.neigh.default.gc_thresh2 = 15360
+                # - net.ipv4.neigh.default.gc_thresh3 = 16384
+                # Ref: https://github.com/aws/aws-parallelcluster-cookbook/pull/1004
+
+                    # Define the sysctl values
+                    declare -A sysctl_values=(
+                        ["net.ipv4.neigh.default.gc_thresh1"]="0"
+                        ["net.ipv4.neigh.default.gc_thresh2"]="15360"
+                        ["net.ipv4.neigh.default.gc_thresh3"]="16384"
+                    )
+
+                    set_sysctl_values() {
+                        for key in "${!sysctl_values[@]}"; do
+                            echo "$key = ${sysctl_values[$key]}" | sudo tee -a "$1"
+                        done
+                    }
+
+                    CONFIG_FILE="/etc/sysctl.d/99-hpc-ready-ami.conf"
+                    sudo touch "$CONFIG_FILE"
+                    sudo truncate -s 0 "$CONFIG_FILE"
+                    set_sysctl_values "$CONFIG_FILE"
+
+                    # Apply the changes
+                    sudo sysctl -p "$CONFIG_FILE"
+                }
+
+                handle_ubuntu_22.04() {
+                    logger "Optimizing Ubuntu 22.04" "INFO"
+                    disable_select_cron_tasks
+                    disable_deeper_cstates
+                    custom_sysctl_settings
+                }
+
+                handle_rhel_9() { 
+                    logger "Optimizing RHEL 9" "INFO"
+                    disable_select_cron_tasks
+                    disable_deeper_cstates
+                    custom_sysctl_settings
+                }
+
+                handle_rocky_9() {
+                    logger "Optimizing Rocky Linux 9" "INFO"
+                    disable_select_cron_tasks
+                    disable_deeper_cstates
+                    custom_sysctl_settings
+                }
+
+                handle_amzn_2() {
+                    logger "Optimizing Amazon Linux 2" "INFO"
+                    disable_select_cron_tasks
+                    disable_deeper_cstates
+                    custom_sysctl_settings
+                }
+
+                # Main function
+                main() {
+                    detect_os_version
+                    handle_${OS}_${VERSION}
+                }
+
+                # Call the main function
+                main "$@"
+
+
+              EOF
+            - chmod +x common.sh optimize-performance.sh
+            - ./optimize-performance.sh
